### ISSUE TITLE
File attachement with AJAX

### ISSUE THREAD

**Issue by mm-tom** [pixelandtonic/ContactForm#17]
I'm having trouble receiving attachments when using AJAX form submission.

I'm passing the form data through with:

```
var data = new FormData(this);
```

Because serialize() won't work on file fields, but unfortunately this still isn't working (email is sent, attachment ignored).

Any ideas?

**Comment by Bronskiy** [comment]
There is an answer https://craftcms.stackexchange.com/a/21386/5587
