### ISSUE TITLE
Additional Fields Value

### ISSUE THREAD

**Issue by ghost** [pixelandtonic/ContactForm#21]
Is it possible to retrieve the value of an additional field? I've tried `message.message[Phone]` and other combinations but it doesn't return anything. 

This is my full field `<input class="fieldItem__textInput" type="phone" name="message[Phone][]" id="phone" placeholder="Phone" value="{% if message is defined %}{{ message.message[Phone] }}{% endif %}" />`

**Comment by melanierichards** [comment]
Hi @takobell, is your last comment on this issue current? Looking to do the same thing.
