### ISSUE TITLE
fromEmail is incorrect?

### ISSUE THREAD

**Issue by skeppit** [pixelandtonic/ContactForm#22]
I'm really confused about the fact that the fromEmail is not to be found in the mail that I am receiving. Not even as the reply address ... the reply address is the address of the admin. If I fill in "blabla@blabla.com" as "fromEmail" ... I expect to receive the form at the address which is configured within the plugin with the "fromEmail" as "from/reply" address. This seems to be some kind of bug?

**Comment by ademers** [comment]
I just noticed that same thing. Has anyone found a solution/workaround? Version 1.4 on Craft Pro 2.2.2607

**Comment by outhouse** [comment]
After a few hours thinking this was a bug, I checked email headers coming from the contact form, and of course the Reply-To field was correctly populated with the fromEmail from the contact form. All I had to do was simply click reply in gmail, and the correct email address was there.

For my client's use case however, this was not ideal, as they needed to forward mail along to others in their organization for a response. My hacky solution was to modify line 47 in services/ContactFormService.php:

```
$email->body      = 'Reply To: ' . $message->fromEmail . ' Message: ' . $message->message;
```

This puts the fromEmail explicitly in the message body. Hope someone finds it useful.

**Comment by takobell** [comment]
As @outhouse noted From Email is set to the what is defined in the contact form's setting and the reply to field is set to the email address the person entered using the contact form.  This was done because many email server saw the "from" address in the email differed from the domain the email originated form and marked it as SPAM.

**Comment by beneklisefski** [comment]
How would I alter the code from @outhouse to create a line break or double line break between the reply to email and the message? As it is, they run together on a single line.
