### ISSUE TITLE
Required Fields

### ISSUE THREAD

**Issue by br-designer** [pixelandtonic/ContactForm#23]
Hi, just wondering if there would be any future updates that add required fields? Essentially giving the client the ability to choose which input fields are required, including an error if the user does not enter information. Thanks in advance!

**Comment by achord** [comment]
That would be a nice feature

**Comment by takobell** [comment]
That's beyond the scope of this plugin.  Contact Form is purposely light-weight.  There are [plenty](https://straightupcraft.com/craft-plugins/sprout-forms) [of](https://straightupcraft.com/craft-plugins/a-m-forms) [other](https://straightupcraft.com/craft-plugins/form-builder) [more](https://straightupcraft.com/craft-plugins/media-surgery-informal-forms) [full-featured](https://straightupcraft.com/craft-plugins/formerly) form builder/contact plugins available.
