### ISSUE TITLE
Feature Request: Ability to send to different email address

### ISSUE THREAD

**Issue by brettdewoody** [pixelandtonic/ContactForm#26]
Would be great if it were possible to pass a hidden `contactForm/toEmail` field to override the default To Email field. Can I put in a feature request for this?

**Comment by nickdunn** [comment]
Yes please!

**Comment by shoeshine** [comment]
+1

**Comment by Kashkin** [comment]
+1

**Comment by chrisrowe** [comment]
+1 on this please

**Comment by bradfordbradford** [comment]
+1

**Comment by ohlincik** [comment]
This approach opens your forms to SPAM. A better approach would be to store the toEmail in your entry and pull it out just before the form is processed.

**Comment by Ottergoose** [comment]
Came here to ask for this too. Perhaps the easiest way to prevent spam would be to have a white-list of approved "send to" addresses could be entered in the settings area?

**Comment by krazyjakee** [comment]
+1 Need a solution for this

**Comment by madebyspark** [comment]
+1 on this

**Comment by knynkwl** [comment]
+1

**Comment by migswd** [comment]
+1

**Comment by pellens** [comment]
+1

**Comment by m3ndi3** [comment]
Yes definitely look for a solution for this too! I need multiple contact forms to different addresses :/

**Comment by efedorenko** [comment]
+1

**Comment by takobell** [comment]
Resolved in 1298ed428f3aa92.  Will be merged into master when 1.6 is ready for release.
