### ISSUE TITLE
Flash message not set

### ISSUE THREAD

**Issue by olsp** [pixelandtonic/ContactForm#261]
It seems like the flash messages aren't set.

When using the code from the docs, no flash message is shown:

```
{% if craft.app.session.hasFlash('notice') %}
   <p class="message notice">{{ craft.app.session.getFlash('notice') }}</p>
{% elseif craft.app.session.hasFlash('error') %}
   <p class="message error">{{ craft.app.session.getFlash('error') }}</p>
{% endif %}
```

`{{ dump( craft.app.session ) }}` outputs the following:

```
craft\web\Session {#201 ▼
  -_events: []
  -_eventWildcards: []
  -_behaviors: array:1 [▼
    "session" => craft\behaviors\SessionBehavior {#199 ▼
      +owner: craft\web\Session {#201}
      -_attachedEvents: []
      +authAccessParam: "84db923b1a58840fd78796ffb34fa2e1__auth_access"
      +assetBundleFlashKey: "__ab"
      +jsFlashKey: "__js"
    }
  ]
  +flashParam: "84db923b1a58840fd78796ffb34fa2e1__flash"
  +handler: null
  #_forceRegenerateId: null
  -_cookieParams: array:4 [▼
    "domain" => ""
    "secure" => true
    "httpOnly" => true
    "sameSite" => null
  ]
  -frozenSessionData: null
  -_hasSessionId: true
}
```

### Additional info

- Craft version: 5.0.0-beta.9 
- Plugin version: 3.1.0

**Comment by brandonkelly** [comment]
Craft 5 uses the `success` key for successful flash messages, rather than `notice`. Just updated the readme to clarify that.

**Comment by iamkeir** [comment]
@brandonkelly a bit confused here - in the context of Craft 5, the contact form plugin sets a successful flash as `success` but Craft 5 itself still uses `notice`?

Ref: https://docs.craftcms.com/api/v5/craft-web-session.html#method-getflash
