### ISSUE TITLE
Add Field Variables to subject line

### ISSUE THREAD

**Issue by CreateSean** [pixelandtonic/ContactForm#262]
### Description
In the contact form plugin settings I'd like to be able to assign field variables to the subject text along the lines of this

`New message from { message.fromName ?? 'No Name' } Company Website name contact form`

I tried the above but it just outputs the text and not the value of the form field.

### Steps to reproduce

1.
2.

### Additional info

- Craft version: 5.0.0
- PHP version: 8.2.17
- Database driver & version:
- Plugins & versions: contact form 3.1.0

**Comment by i-just** [comment]
Hi, thanks for reaching out! 

At the moment, that’s not possible via the plugin’s settings. The “Subject Text” will be prepended to the email’s Subject to flag that it comes from the Contact Form. So, if you have your “Subject Text” set to “New message from My Website” and the person filling out the form sets the `subject` to “About Something”, the subject will be: “New message from My Website - About Something”.

You can, however, manipulate the subject via `Mailer::EVENT_BEFORE_SEND` event (from a module or a plugin):
```
Event::on(Mailer::class, Mailer::EVENT_BEFORE_SEND, function(SendEvent $e) {
    $subject = $e->submission->subject;
    $settings = \craft\contactform\Plugin::getInstance()->getSettings();
    $e->message->setSubject("{$settings->prependSubject} - $subject - additional message");
});
```

I hope this helps!
