### ISSUE TITLE
How to modify so emails are sent using system email template?

### ISSUE THREAD

**Issue by schmoove** [pixelandtonic/ContactForm#29]
Have been reading up on the email hooks:

http://buildwithcraft.com/docs/plugins/hooks-reference#registerEmailMessages

But not entirely sure how the plugin should be modified to use the system's email template - any suggestions would be much appreciated!

**Comment by takobell** [comment]
This is beyond the scope of this plugin.  Contact Form is purposely light-weight.  There are [plenty](https://straightupcraft.com/craft-plugins/sprout-forms) [of](https://straightupcraft.com/craft-plugins/a-m-forms) [other](https://straightupcraft.com/craft-plugins/form-builder) [more](https://straightupcraft.com/craft-plugins/media-surgery-informal-forms) [full-featured](https://straightupcraft.com/craft-plugins/formerly) form builder/contact plugins available.
