### ISSUE TITLE
Failing validation doesn't expose value of additional fields to template

### ISSUE THREAD

**Issue by hamishtaplin** [pixelandtonic/ContactForm#34]
If you add additional fields by splitting the 'message' field into an array (as per the readme) and validation fails, the plugin doesn't return the array of values on the 'message' field (so you can pre-fill values)—it just returns the content of the 'body' property of that array.

**Comment by lindseydiloreto** [comment]
+1 ... this particularly sucks on large forms.

Is there any known workaround?

**Comment by cole007** [comment]
It is possible to resolve this by hacking `contactform/controllers/ContactFormController.php` 

For line 133 change:

    $message->message = $savedBody;

to:

    $message->message = $postedMessage;

This will expose the message fields that have been created as an array. To access in your template just use, eg:

    {{ message.message['body'] }}

Be interested to know if there are any security or other implications for this (apart from hacking the core files).

**Comment by takobell** [comment]
In our current implementation, a proper solution for this would be pretty involved and messy. Contact Form is purposely light-weight.  There are [plenty](https://straightupcraft.com/craft-plugins/sprout-forms) [of](https://straightupcraft.com/craft-plugins/a-m-forms) [other](https://straightupcraft.com/craft-plugins/form-builder) [more](https://straightupcraft.com/craft-plugins/media-surgery-informal-forms) [full-featured](https://straightupcraft.com/craft-plugins/formerly) form builder/contact plugins available.
