### ISSUE TITLE
Plugin doesn't redirect to the locale the form was posted from

### ISSUE THREAD

**Issue by megatrond** [pixelandtonic/ContactForm#36]
Have two locales on site, English and Norwegian.

When submitting the form, I am always redirected to the English locale.

Redirect param is normal: `<input type="hidden" name="redirect" value="kontakt/takk">`

**Comment by seppentoni** [comment]
You need to includ the locale in the redirect url.

For example like this:

`<input type="hidden" name="redirect" value="{{ entry.url }}?message=thankyou">`
