### ISSUE TITLE
Unable to resolve the request "contactform/sendMessage"

### ISSUE THREAD

**Issue by tyssen** [pixelandtonic/ContactForm#37]
I'm getting this error when trying to submit a form that is included at the bottom of all pages.

I have 

    <input type="hidden" name="action" value="contactform/sendMessage">
    <input type="hidden" name="redirect" value="message-received">

which I've taken from the docs. I'm running the latest Craft build and v1.4 of the plugin.

Is there anything else I'm missing?

**Comment by tyssen** [comment]
Action value needs to be camelCase: `contactForm/sendMessage`.

**Comment by takobell** [comment]
Resolved using `contactForm/sendMessage`. https://twitter.com/tyssen/status/636108738659663872
