### ISSUE TITLE
Is it possible to utilise an environment variable in the plugin config?

### ISSUE THREAD

**Issue by rgbjay** [pixelandtonic/ContactForm#38]
It would be a nice feature to allow the use of environment variables in the to Field in the plugin settings.

We are utilising the plugin on a site with 4 differing environments, each could do with a different address as the to address for testing purposes.

**Comment by takobell** [comment]
Resolved via aa6958e0c9f2e524278 which is fully multi-environment aware. Will merge into master for next release.
