### ISSUE TITLE
Question about succesfull submit

### ISSUE THREAD

**Issue by celien-n** [pixelandtonic/ContactForm#40]
Since we have a one page website I would always like to return to the same page, using an anchor to direct to the right section. I've managed to do so. 
The errors are showing as expected, and the return is correct in case of error and on success. 
I would like to detect if the form has successfully submitted so I can display a message to the user. How can I check for this?

**Comment by terrysmyth** [comment]
i did this:

{% if craft.request.getQuery('from')|length %}
  <div class="thankyou">
  <p>Thanks for sending that in, {{ craft.request.getQuery('from') }}!</p>
  </div>
{% endif %}

so the div only shows up IF there is a result from the getQuery.

hope it helps

**Comment by celien-n** [comment]
I can't seem to get it to work and I suspect it has to do with the fact that I'm submitting the form using the post method, not the get. Is there a way to check for a successful submit without using get?

**Comment by celien-n** [comment]
I solved it this way: 
 <input type="hidden" name="redirect" value="/?submit=success&#contact">

 {% if craft.request.getQuery('submit')=="success" %}  
     <div id='success_message'>
        Thank you, your message is sent! 
    </div>
{% endif %}
