### ISSUE TITLE
Allow empty prepends

### ISSUE THREAD

**Issue by alexw23** [pixelandtonic/ContactForm#43]
These two settings when left empty keep resorting back to their defaults. How would you suggest we fix it to allow for empty prepends? I.e. the sender and the subject are exactly what is sent?

https://github.com/pixelandtonic/ContactForm/blob/4cd257dc83615e0fd468fa14e660bed0743c2ed9/contactform/templates/_settings.html#L20

https://github.com/pixelandtonic/ContactForm/blob/4cd257dc83615e0fd468fa14e660bed0743c2ed9/contactform/templates/_settings.html#L29

**Comment by takobell** [comment]
Resolved in 9718a1a085a14c46706. Will merge into master when 1.6 release is ready.
