### ISSUE TITLE
Feature Request: save form submissions in database

### ISSUE THREAD

**Issue by pellens** [pixelandtonic/ContactForm#44]
It would be perfect if submissions are saved in the database and an overview of these submissions would be available in the admin area.

This could be a perfect backup tool for the submissions, as well open up new possibilities to manage contacts, potential clients, ...

**Comment by takobell** [comment]
Contact Form is purposely light-weight.  There are [plenty](https://straightupcraft.com/craft-plugins/sprout-forms) [of](https://straightupcraft.com/craft-plugins/a-m-forms) [other](https://straightupcraft.com/craft-plugins/form-builder) [more](https://straightupcraft.com/craft-plugins/media-surgery-informal-forms) [full-featured](https://straightupcraft.com/craft-plugins/formerly) form builder/contact plugins available.

You can also write an additional plugin similar to [this one](https://straightupcraft.com/craft-plugins/contact-form-receipts) that listens to the onBeforeSend event and saves whatever you want to the database.
