### ISSUE TITLE
Doesnt submit or redirect? (Just help)

### ISSUE THREAD

**Issue by terrysmyth** [pixelandtonic/ContactForm#45]
Hello,

I have used this plugin on three different occasions with no issues whatsoever, that is why I am so dumbstuck on why it doesnt work now. 

I have used the exact same code on all sites - tested the email from craft - and for some reason, on submit nothing happens. The site reloads, all the inputs are still there. Here is my redirect:

<input type="hidden" name="redirect" value="{{siteUrl}}?message=thankyou">

I have tried redirecting to another page too. Im sure there is something so small and easily fixable that i am missing. If anyone can highlight my oversight (or any normally over looked areas that i should look in to), that would be great. THANKS!

**Comment by takobell** [comment]
Check your `craft/storage/runtime/logs` folder for any related errors.  If nothing is there, share code you're using for the contact form.
