### ISSUE TITLE
Ajax POST is sending HTML of home page as reponse

### ISSUE THREAD

**Issue by bravokiloecho** [pixelandtonic/ContactForm#47]
I'm using the described Ajax method to handle contact form submissions and receiving as a response the full HTML markup from the homepage rather than the JS object that the Readme describes.

I'm pretty sure I'm following the example but just to be sure here is JS I have...

```
var sendValidForm = function( $form ) {
	var data = $form.serialize();
    // I'm getting the URL from a data attribute on the form in the template
    // which looks like this: data-post-to="{{ siteUrl }}"
	var postTo = $form.data('post-to');

	console.log('Form data');
	console.log(data);

	// Send it to the server
	$.post( postTo , data, function( response ) {
		if ( response.success ) {
			afterSubmission( $form );
		} else {
			console.log(response);
			formError( $form, 'An error occurred. Please try again.' );
		}
	});
};
```

I'm using version 1.7.0 of the plugin, version 2.5.2761 of Craft, and it's running on PHP 5.6.10. I can also confirm that the dashboard shows the plugin is installed and enabled.

Any help would be much appreciated, thanks!

**Comment by takobell** [comment]
I'd guess something in your `.htaccess` file is intercepting/redirect the request.

**Comment by bravokiloecho** [comment]
Thanks for your response. I had a look at the `.htaccess` file and I don't think I'd added anything there. But I grabbed the version that comes with the standard Craft install and tried using it and I'm still seeing the same problem.

I checked the request in Chrome's console and can't find anything amiss there.

Do you have any other thoughts of what I might check? Thanks!

**Comment by takobell** [comment]
Does your server have something like mod_security or Suhosin installed? Might have an overly aggressive security rule blocking the request.

**Comment by bravokiloecho** [comment]
I'm currently running the site locally through MAMP so I don't think that's the problem.

In the Chrome web inspector the network tab is showing a status code of `200` with a request method of `POST` and I can see that it's getting the form data. So everything seems to be working fine up to that point...

**Comment by bravokiloecho** [comment]
Here's a quick screenshot:

![image](https://cloud.githubusercontent.com/assets/5556900/12882793/e1aaab6c-ce4b-11e5-85fa-5be4ee8447a6.png)

**Comment by bravokiloecho** [comment]
I figured out the problem! It was missing this line in the form:

```<input type="hidden" name="action" value="contactForm/sendMessage">```

Stupid of me but I guess I assumed this wasn't necessary if Posting with Ajax.

Thank you very much for your time and apologies for not spotting this problem before.
