### ISSUE TITLE
To Email Limitation

### ISSUE THREAD

**Issue by taylorcollins** [pixelandtonic/ContactForm#49]
I have an email address set up at a domain with a hyphen. When I use that email as the "To Email" in the plugin settings, I don't receive the mail. The address works otherwise. Other addresses work as the "To Email" also.
Could it be causing a problem because of the hyphen? ex. info@taylor-collins.com

**Comment by takobell** [comment]
Hyphened domains work fine.  Most likely it's an email delivery issue.  i.e. going to a SPAM folder or you're using phpmail or sendmail which are notoriously unreliable at email deliver.  Try using a proper SMTP server or a transactional email provider like mandrillapp.com
