### ISSUE TITLE
Failed Submission Set Reload at div id

### ISSUE THREAD

**Issue by aaronsransom** [pixelandtonic/ContactForm#52]
Is there anyway to stop the form from reloading at the top of the page and instead have the page reloaded at a particular id location (e.g. <form id="myFormID">) when errors are detected? Depending on where the form is located, a user may have no idea submission failed unless they scroll down to see errors.

**Comment by takobell** [comment]
Usage questions should be posted over on craftcms.stackexchange.com or on the Craft Slack group https://craftcms.com/community#slack
