### ISSUE TITLE
SPAM Problems + Integrate Google reCAPTCHA with ContactForm

### ISSUE THREAD

**Issue by challahan** [pixelandtonic/ContactForm#53]
I'm receiving about 2 SPAM messages a day, even though I've enabled the honeypot field.  I'm not sure if I've implemented the feature wrong or not.  When I try simulating it in my browser by filling in the field, everything works.  

The form is here under Get In Touch Today at the bottom, by the way: http://www.ideabasekent.com

Has anyone had success integrating this with Google's reCAPTCHA service?  I find Google's documentation and instructions to be really confusing.

**Comment by takobell** [comment]
https://github.com/selvinortiz/craft.spamguard

FFR, usage questions should be posted over Craft Stack Exchange site: https://craftcms.stackexchange.com/
