### ISSUE TITLE
Line break in emails

### ISSUE THREAD

**Issue by nmsdvid** [pixelandtonic/ContactForm#59]
When receiving the emails the info in the emails are in one line. Is there a way to add line breaks ?

**Comment by takobell** [comment]
If you're viewing the email as plan text, any new lines will be preserved, but the only thing we do for the html email by default is take the plain text one and run it through Markdown.  If you want more control over it than that, you can write a [plugin](https://pluginfactory.io/) that listens to the [onBeforeSend](https://github.com/pixelandtonic/ContactForm#the-contactformbeforesend-event) event and modifies the contents of plain text and HTML to however you wish.

**Comment by distinctm** [comment]
I'm seeing this too, viewing the emails as HTML. 

> Content-Type: text/plain; charset=us-ascii
> 
> message: test  
> formType: Ask a Question  
> itemID: 1234
> 
> 
> Content-Type: text/html; charset=us-ascii
> 
> <p>message: test  
> formType: Ask a Question  
> itemID: 1234</p>

**Comment by Friksel** [comment]
Just for people finding this issue as me to look for a solution, and are using custom templates via the Contact Form Extensions plugin; you can also convert the linebreaks to `<br/>`s from within the email templates with the `nl2br` Twig filter like so:

```
<p>{{ submission.message.body|nl2br }}</p>
```
