### ISSUE TITLE
Show fromEmail and fromName in message body

### ISSUE THREAD

**Issue by KingDaddy** [pixelandtonic/ContactForm#62]
Is it possible to add in an option to show the sender's email address and name in the message body?

Quite often when these emails are received they are forwarded on to the relevant recipient and therefore losing the reply to address (fromName), it would be very useful if the sender's details are included in the message body as it already does for other fields in the form.

**Comment by zizther** [comment]
+1 For this

**Comment by joshua-martin** [comment]
You can modify **services/ContactFormService.php** to get fromName and fromEmail to show.

I'm not sure if you have done this yourselves and are asking for it to be in the official plugin or not, though I wanted to document how I've done this already.

Replace Line 57
~~~~$email->htmlBody = str_replace(array('{', '}'), array('&lbrace;', '&rbrace;'), $message->htmlMessage);~~~~

With
~~~~
$email->htmlBody = '<strong>Name</strong>: '.$message->fromName;
$email->htmlBody .= '<strong>Email Address:</strong> '.$message->fromEmail;
$email->htmlBody .= str_replace(array('{', '}'), array('&lbrace;', '&rbrace;'), $message->htmlMessage);
~~~~

**Comment by awhitehouse104** [comment]
@joshua-martin Great fix, note one should wrap each with <p/> tags for consistent formatting with the rest of the message.

**Comment by discoverRG** [comment]
+1 for adding this into the official plugin.

**Comment by takobell** [comment]
This can be achieved without modifying core files via the onBeforeMessageCompile event: https://github.com/pixelandtonic/ContactForm#the-contactformbeforemessagecompile-event

**Comment by mckelvey** [comment]
Hmmm... I did attempt to use the before message compile event, and found that the event was firing fine, except that all event values (as shown in the readme) were NULL; alteration of the values had no impact either. I can’t say that this Craft install is pristine, but it is pretty unadorned and recent (v2.6.2797). (I’ve edited the plugin core for the time-being.)

**Comment by davidteal** [comment]
I also had similar issues to @mckelvey where the params were null. Attached is a non-core edit fix that seemed to work for me but I had to copy a lot of the message building code from the controller as this is skipped by `if ($event->message && $event->messageFields)`

[onBeforeMessageCompile.txt](https://github.com/pixelandtonic/ContactForm/files/787192/onBeforeMessageCompile.txt)

**Comment by mckelvey** [comment]
Thanks @davidteal!
