### ISSUE TITLE
All emails going to gmail spam folder

### ISSUE THREAD

**Issue by planktonWD** [pixelandtonic/ContactForm#69]
Hi guys,

Great plugin. My issue is that all my emails are going to gmails spam folder. I have had to create a hardcoded subject and create a filter in gmail to stop it going to spam.

Have you guys experienced this before? Gmails spam message is 'Why is this message in Spam? It's similar to messages that were detected by our spam filters'. Is there a setup for fromEmail and subject etc that you know of that stops it going to spam? My sender name is the same as domain name so I know it's not that issue.

Thanks!

**Comment by takobell** [comment]
There are some good tips here for ensuring reliable email delivery: https://blog.codinghorror.com/so-youd-like-to-send-some-email-through-code/
