### ISSUE TITLE
Email is not valid on Mobile Safari

### ISSUE THREAD

**Issue by DanielEytan** [pixelandtonic/ContactForm#70]
I use the ContactForm in the footer of this website: http://cartoonmuseum.ch/en/

It works fine except in Mobile Safari (iOS 10.2.1). Also tested the ContactForm in Mobile Chrome and it works as it should.

Error message in Mobile Safari: «Your Email is not a valid email address».

No idea what the issue could be.

Best, Daniel

**Comment by takobell** [comment]
This will end up being a Mobile Safari bug with their implementation of `type="email"` on the input form.

**Comment by DanielEytan** [comment]
Thanks for the help.
