### ISSUE TITLE
Custom Fields Issue

### ISSUE THREAD

**Issue by nicklanehq** [pixelandtonic/ContactForm#79]
We've added a few custom fields to a basic implementation of this plugin and they are not being included in the body of the email's message. This includes a phone input and topic dropdown select. The install is running the latest version, 1.8.1. We are not finding anything related in the Craft logs either.

Our template code is shown here, https://gist.github.com/nicklanehq/e7bc9f43974d2132915e8f2f9e57e6f8

**Comment by brandonkelly** [comment]
You are probably overriding what `message` param will be sent to the server with this line:

```html
<textarea name="message" name="message[body]" id="message" class="required">{% if message is defined %}{{ message.message }}{% endif %}</textarea>
```

Try removing `name="message"`, keeping the 2nd `name` attribute only.

**Comment by nicklanehq** [comment]
Thanks @brandonkelly, that resolved it.
